### ISSUE TITLE
错误信息返回里加了url参数，和写死code，是为什么呢？

### ISSUE THREAD

**Issue by huyinghuan888** [duxphp/duxphp-archive#1]
/**
     * 返回错误数据
     * @param int $code
     * @param string $msg
     * @param string $url
     */
    public function error($msg = '', $code = 500, $url = '') {
        if (empty($msg)) {
            $msg = \dux\Dux::$codes[$code];
        }
        $data = [
            'code' => $code,
            'message' => $msg,
            'url' => $url
        ];
        \dux\Dux::header(200, function () use ($data) {
            $this->returnData($data);
        });
    }

老大，有两个问题不解，向你请教。。:) 
1、这里 header 写死了 200 状态码，是为什么呢？另外如果是必须写死，那 $code 的传参是不是就没有必要了。
2、错误返回信息里加了 $url 项，这个在 api 开发中用在哪些场景呢？

谢谢赐教！！

**Comment by dux-web** [comment]
非程序内错误为500状态码  200状态码为程序内容执行 解析json内部code参数可获取程序内状态
